%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Author: https://github.com/jtleek/capitalIn21stCenturyinR
%%% Author: knitr/beamer by Patrick Toche, December 2014
%%% Author: data/content by Thomas Piketty, 2013-2014
%%% This replicates a December 2014 presentation at Sao Paulo by Thomas Piketty
%%% The .Rnw file is the 'master', other files produced by knitr compilation
%%% To compile in R: library(knitr); knit("slides.Rnw");
%%% To compile in Rstudio: 'Compile PDF' menu command
%%% The 'pictures' directory contains images inserted with \includegraphics
%%% The 'figures' directory contains pdf created and inserted by knitr
%%% Delete the 'cache' directory to recreate pdf graphics
%%% The 'SaoPaulo' directory contains pdf of original powerpoint for reference
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%% \PassOptionsToPackage loads options for packages loaded by beamer class
\PassOptionsToPackage{obeyspaces}{url}% url package loaded by hyperref
\PassOptionsToPackage{usenames,dvipsnames,svgnames}{xcolor}% named colors
\PassOptionsToPackage{%
    unicode = {false}%
    , colorlinks = {true}%
    , linkcolor = {MidnightBlue}%
    , filecolor = {MidnightBlue}%
    , citecolor = {MidnightBlue}%
    , urlcolor = {MidnightBlue}%
    , breaklinks = {false}%
    , plainpages = {true}% page number anchors as plain arabic
    , bookmarks = {true}%
    , bookmarksnumbered = {true}%
    , bookmarksopen = {true}%
    , backref = {false}%
    , pdfusetitle = {false}% false required for \includeonlyframeslist hack
    , pdfpagemode = {UseNone}% UseThumbs, UseOutlines, FullScreen, UseNone
    , pdfpagetransition = {Wipe /Di -45}%
    , pdfpagelayout = {SinglePage}%
    , pdfpagelabels = {false}% fix for beamer bug for some classes
    , pdfstartpage = {1}%
    , pdfstartview = {FitV}%
    , pdffitwindow = {false}%
    , pdfcenterwindow = {true}%
    , pdfmenubar = {true}%
    , pdfdisplaydoctitle = {true}%
}{hyperref}

%%%%%%%%%% Preamble Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[t]{beamer}
%%% Select frames to be included in presentation
% \includeonlyframes{} takes a comma-separated list *without spaces*
%\input{slidesPikettySaoPaulo2014}% list of frames for inclusion
%\input{slidesCurrent}% frames being debugged

%%%%%%%%%% Set Document Information %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\title{Capital in the 21st Century}
\author[Thomas Piketty]{Thomas Piketty\inst{1}\inst{2}}
\institute{$^1$Paris School of Economics \\
  Sao Paulo, 26 November 2014 \bigskip\bigskip \\
  $^2$translated to beamer via knitr by Patrick Toche \\
  \href{mailto:contact@patricktoche.com}{contact@patricktoche.com} \\
  Based on collaborative effort led by Jeff Leek \\
  \url{https://github.com/jtleek/capitalIn21stCenturyinR} \\
  All copyright claims with Professor Piketty
}
\date{December 2014}

%%%%%%%%%% Set Beamer Options %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\usetheme{piketty}

%%%%%%%%%% Load Latex Packages %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage[T1]{fontenc}% font encoding, load before inputenc
\usepackage[utf8]{inputenc}% character inputing, load after fontenc
\usepackage{lmodern}
\usepackage{booktabs}% fancy tables
\usepackage[flushleft]{threeparttable}% fancy tables
\usepackage{adjustbox}% combine with threeparttable package
\usepackage{verbatim}% pass text as unprocessed strings / comment out

%%%%%%%%%% Set Miscellani %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\setcounter{secnumdepth}{3}%
\setcounter{tocdepth}{3}%
\setlength{\abovecaptionskip}{0pt}%
\setlength{\belowcaptionskip}{0pt}%
\renewcommand{\insertpagenumber}{}% suppress page numbers

%%%%%%%%%% Load knitr Options %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<'setup', include=FALSE>>=
library(knitr)

### Set compilation options
# option warning = FALSE set locally for easy toggle on/off while debugging
opts_chunk$set(echo = FALSE, comment = NA, concordance = TRUE, warning = FALSE, cache = TRUE)

# Set smaller font size for chunks (for code display):
opts_chunk$set(size = 'footnotesize')

# Set figure size and resolution
opts_chunk$set(dev = c('pdf','png'), fig.path = 'figures/color/', fig.align='center', fig.height = 5, fig.width = 8, dpi = 300)

# evaluate fig.cap after a chunk is evaluated
opts_knit$set(eval.after = 'fig.cap')

# TeX styles in tex document, CSS styles in HTML document
opts_knit$set(self.contained = TRUE)

# Rename figures to remove -1 suffix
local({# only works for pdf
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    name = sub('-1([.][a-z]{3,4})$', '\\1', x)
    if (name != x) file.rename(x, name)
    hook_plot(name, options)
  })
}) 

### Load Libraries:
# setwd("~/R/capital21c/Github/Slides")# temp for convenience
library(ggplot2)
library(scales)
library(xlsx)
library(reshape2)
library(RColorBrewer)

### Set Color & Shape Scheme
# linetype scheme (experimental, needs a tweak or two)
linePalette <- c("solid", "dotted", "dashed", "dotdash", "longdash", "twodash", "13", "31", "1221")# "33" means 3 units on followed by 3 units off
# shape scheme (is there a package for this?)
shapePalette <- c(17, 2, 16, 1, 15, 0, 18, 5, 24)
# color scheme (with RBrewerColor package)
colorPalette <- colorRampPalette(brewer.pal(9, "Set1"))(9)
# bw scheme (uncomment both lines to activate)
  # colorPalette <- rep("#000000", 9)# black and white figures in 'Piketty' style
  # opts_chunk$set(fig.path = 'figures/bw/') # save in sub-directory
@


<<'data', include=FALSE>>=
### Load Data:
# Piketty denotes TS1.1 the sheets for Chapter 1.1, etc.
# I denote df1.1 the dataframe for Figure 1.1, etc.
# I denote df0.1 the dataframe for Figure I.1 (I stands for Introduction but is all too easily confused with 1)

## Figure I.1 / TSI.1 / top decile / USA
ts0.1 <- read.xlsx("../Piketty2014FiguresTables/Chapter0TablesFigures.xlsx",
  sheetName = "TSI.1", rowIndex = 7:107, colIndex = 1:2, header = FALSE)
names(ts0.1) <- c("Year", "top_10_is")
df0.1 <- melt(ts0.1, id.vars = "Year")

## Figure I.2 / TSI.2 / private capital / 3 countries
ts0.2 <- read.xlsx("../Piketty2014FiguresTables/Chapter0TablesFigures.xlsx",
  sheetName = "TSI.2", rowIndex = 6:20, colIndex = 1:4, header = FALSE)
names(ts0.2) <- c("Year", "Germany", "France", "Britain")
df0.2 <- melt(ts0.2, id.vars = "Year")

## Figure 2.1 / TS2.1 / world population / 4 continents
ts2.1 <- read.xlsx("../Piketty2014FiguresTables/Chapter2TablesFigures.xlsx",
  sheetName = "TS2.2", rowIndex = 8:17, colIndex = c(25, 27:30), header = FALSE)
names(ts2.1) <- c("Year", "Europe", "America", "Africa", "Asia")
df2.1 <- melt(ts2.1, id.vars = "Year")

## Table TS2.2
# Table S2.2a
ts2.2a <- read.xlsx("../Piketty2014FiguresTables/Chapter2TablesFigures.xlsx",
  sheetName = "TS2.2", rowIndex = 8:28, colIndex = 1:6, header = FALSE)
ts2.2a[, 7] <- c(1:13, 10:13, 10:13) # Create a sequence
names(ts2.2a) <- c("Period", "World", "Europe", "United States", "Africa", "Asia", "Seq")
df2.2a <- ts2.2a[1:13,]
df2.2a <- melt(df2.2a, id.vars = c("Period", "Seq"))
# Create factors Observed / Projected
df2.2a$Type <- as.factor(ifelse(df2.2a$Seq < 10, "Observed", "Projected"))
# Table S2.2b
ts2.2b <- read.xlsx("../Piketty2014FiguresTables/Chapter2TablesFigures.xlsx",
  sheetName = "TS2.2", rowIndex = 8:28, colIndex = 8:23, header = FALSE)
ts2.2b[, 17] <- c(1:13, 10:13, 10:13) # Create a sequence
names(ts2.2b) <- c("Period", "World", "Western Europe", "Eastern Europe", "Russia & Ukraine Belarus Moldavia", "North America", "Latin America", "Northern Africa", "Sub-Shaharan Africa", "China", "India", "Japan", "Australia & New Zealand", "Middle East (Including Turkey)", "Central Asia", "Other Asian Countries", "Seq")
ts2.2b <- melt(ts2.2b, id.vars = "Period")
# Table S2.2c
ts2.2c <- read.xlsx("../Piketty2014FiguresTables/Chapter2TablesFigures.xlsx",
  sheetName = "TS2.2", rowIndex = 8:29, colIndex = 25:30, header = FALSE)
ts2.2c[, 7] <- c(1:14, 11:14, 11:14) # Create a sequence
names(ts2.2c) <- c("Year", "World", "Europe", "United States", "Africa", "Asia", "Seq")
ts2.2c <- melt(ts2.2c, id.vars = "Year")
# Table S2.2d
ts2.2d <- read.xlsx("../Piketty2014FiguresTables/Chapter2TablesFigures.xlsx",
  sheetName = "TS2.2", rowIndex = 8:29, colIndex = 32:47, header = FALSE)
ts2.2d[, 17] <- c(1:14, 11:14, 11:14) # Create a sequence
names(ts2.2d) <- c("Year", "World", "Western Europe", "Eastern Europe", "Russia & Ukraine Belarus Moldavia", "North America", "Latin America", "Northern Africa", "Sub-Shaharan Africa", "China", "India", "Japan", "Australia & New Zealand", "Middle East (Including Turkey)", "Central Asia", "Other Asian Countries", "Seq")
ts2.2d <- melt(ts2.2d, id.vars = "Year")

## Figure 2.2 / TS2.2 / World population
df2.2 <- df2.2a[which(df2.2a$variable == "World"),]

## Figure 2.3 / TS2.4 / Europe + America / Per capita output
ts2.4a <- read.xlsx("../Piketty2014FiguresTables/Chapter2TablesFigures.xlsx",
  sheetName = "TS2.4", rowIndex = 10:16, colIndex = 4:6, header = FALSE)
ts2.4a[, 4] <- as.numeric(row.names(ts2.4a)) # Create a sequence
names(ts2.4a) <- c("Period", "Western Europe", "North America", "Seq")
df2.3 <- melt(ts2.4a, id.vars = c("Period", "Seq"))

## Figure 2.4 / TS2.4 / World / Per capita output
ts2.4b <- read.xlsx("../Piketty2014FiguresTables/Chapter2TablesFigures.xlsx",
  sheetName = "TS2.4",rowIndex = 7:18, colIndex = c(1,3), header = FALSE)
ts2.4b[, 3] <- as.numeric(row.names(ts2.4b)) # Create a sequence
names(ts2.4b) <- c("Period", "World", "Seq")
df2.4 <- melt(ts2.4b, id.vars = c("Period", "Seq"))
# Create factors Observed / Projected
df2.4$Type <- as.factor(ifelse(df2.4$Seq < 8, "Observed", "Projected"))

## Figure 2.5 / TS2.4 / World / Total output
ts2.4c <- read.xlsx("../Piketty2014FiguresTables/Chapter2TablesFigures.xlsx",
  sheetName = "TS2.4",rowIndex = 7:18, colIndex = c(1,2), header = FALSE)
ts2.4c[, 3] <- as.numeric(row.names(ts2.4c)) # Create a sequence
names(ts2.4c) <- c("Period", "World", "Seq")
df2.5 <- melt(ts2.4c, id.vars = c("Period", "Seq"))
# Create factors Observed / Projected
df2.5$Type <- as.factor(ifelse(df2.5$Seq < 8, "Observed", "Projected"))

## Figure 2.6 / TS2.5 / Countries / Inflation
ts2.5 <- read.xlsx("../Piketty2014FiguresTables/Chapter2TablesFigures.xlsx",
  sheetName = "TS2.5", rowIndex = 8:14, colIndex = 1:5, header = FALSE)
ts2.5[, 6] <- as.numeric(row.names(ts2.5)) # Create a sequence
names(ts2.5) <- c("Period", "France", "Germany", "United States", "Britain", "Seq")
df2.6 <- melt(ts2.5, id.vars = c("Period", "Seq"))


## Figure 3.1 / TS???

## Figure 3.2 / TS???

## Figure 4.6 / TS???

## Figure 4.10 / TS???

## Figure 4.11 / TS???


## Figure 5.1 / CTS4.5 / private & public capital / USA & Europe
# Private capital
cts4.5a <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "CTS4.5", rowIndex = 6:20, colIndex = c(1:6), header = FALSE)
names(cts4.5a) <- c("Year", "United States", "Germany", "France", "United Kingdom", "Europe")
cts4.5a[, "Type"] <- "Private capital"
# National capital
cts4.5b <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "CTS4.5", rowIndex = 6:20, colIndex = c(1,7:11), header = FALSE)
names(cts4.5b) <- c("Year", "United States", "Germany", "France", "United Kingdom", "Europe")
cts4.5b[, "Type"] <- "National capital"
# Public capital
cts4.5c <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "CTS4.5", rowIndex = 6:20, colIndex = c(1,12:16), header = FALSE)
names(cts4.5c) <- c("Year", "United States", "Germany", "France", "United Kingdom", "Europe")
cts4.5c[, "Type"] <- "Public capital"
# Net foreign capital
cts4.5d <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "CTS4.5", rowIndex = 6:20, colIndex = c(1,21:25), header = FALSE)
names(cts4.5d) <- c("Year", "United States", "Germany", "France", "United Kingdom", "Europe")
cts4.5d[, "Type"] <- "Net foreign capital"
# Merge data frames
cts4.5 <- rbind(cts4.5a, cts4.5b, cts4.5c, cts4.5d)
rm(list = c('cts4.5a', 'cts4.5b', 'cts4.5c', 'cts4.5d'))
cts4.5[, "Type"] <- factor(cts4.5[, "Type"])
cts4.5 <- melt(cts4.5, id.vars = c("Year", "Type"))
df5.1 <- subset(cts4.5, variable %in% c("United States", "Europe") & Type %in% c("Private capital", "Public capital"))

## Figure 5.2 / CTS4.5 / national & foreign capital / USA & Europe
df5.2 <- subset(cts4.5, variable %in% c("United States", "Europe") & Type %in% c("National capital", "Net foreign capital"))

## Figure 5.3 / TS5.1 / private capital / 9 countries
ts5.1 <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "TS5.1", rowIndex = 5:45, colIndex = 1:10, header = FALSE)
names(ts5.1) <-  c("Year", "United States", "Japan", "Germany", "France", "United Kingdom", "Italy", "Canada", "Australia", "Spain")
df5.3 <- melt(ts5.1, id.vars = "Year")

## Figure 5.3b / TS5.2 / public capital / 9 countries
ts5.2 <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "TS5.2", rowIndex = 5:45, colIndex = 1:10, header = FALSE)
names(ts5.2) <-  c("Year", "United States", "Japan", "Germany", "France", "United Kingdom", "Italy", "Canada", "Australia", "Spain")
df5.3b <- melt(ts5.2, id.vars = "Year")

## Figure 5.4 / TS5.12 / private capital ratio / 9 countries
ts5.12 <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "TS5.12", rowIndex = 5:45, colIndex = 1:10, header = FALSE)
names(ts5.12) <- c("Year", "United States", "Japan", "Germany", "France", "United Kingdom", "Italy", "Canada", "Australia", "Spain")
df5.4 <- melt(ts5.12, id.vars = "Year")

## Figure 5.5 / TS5.1 + TS5.2 / public & private capital / 9 countries
df5.5 <- merge(df5.3, df5.3b, by = c("Year", "variable"))
names(df5.5) <- c("Year", "variable", "Private", "Public")
df5.5 <- melt(df5.5, id.vars = c("Year", "variable"))
names(df5.5) <- c("Year", "variable", "Type", "value")

## Figure 5.6 / TS5.11 / market/book value of corporations  / 7 countries
ts5.11 <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "TS5.11", rowIndex = 5:45, colIndex = 1:9, header = FALSE)
names(ts5.11) <- c("Year", "United States", "Japan", "Germany", "France", "United Kingdom", "Italy", "Canada", "Australia")
ts5.11 <- ts5.11[, c("Year", "United States", "Japan", "Germany", "France", "United Kingdom", "Canada", "Australia")] # Drop Italy as data is empty
df5.6 <- melt(ts5.11, id.vars = "Year")

## Figure 5.7 / TS5.3 + TS5.5 / public & private capital / 9 countries
ts5.3 <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "TS5.3", rowIndex = 5:45, colIndex = 1:10, header = FALSE)
names(ts5.3) <- c("Year", "United States", "Japan", "Germany", "France", "United Kingdom", "Italy", "Canada", "Australia", "Spain")
ts5.3 <- melt(ts5.3, id.vars = "Year")
ts5.5 <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "TS5.5", rowIndex = 5:45, colIndex = 1:10, header = FALSE)
names(ts5.5) <- c("Year", "United States", "Japan", "Germany", "France", "United Kingdom", "Italy", "Canada", "Australia", "Spain")
ts5.5 <- melt(ts5.5, id.vars = "Year")
df5.7 <- merge(ts5.3, ts5.5, by = c("Year", "variable"))
names(df5.7) <- c("Year", "variable", "National", "Foreign")
df5.7 <- melt(df5.7, id.vars = c("Year", "variable"))
names(df5.7) <- c("Year", "variable", "Type", "value")

## Figure 5.8 / CTS12.3 / world capital/income ratio
cts12.3 <- read.xlsx("../Piketty2014FiguresTables/Chapter5TablesFigures.xlsx",
  sheetName = "CTS12.3", rowIndex = 5:28, colIndex = 1:2, header = FALSE)
names(cts12.3) <- c("Year", "Capital")
df5.8 <- melt(cts12.3, id.vars = "Year")
# Create factors Observed / Projected
df5.8$Type <- as.factor(ifelse(df5.8$Year < 2011, "Observed", "Projected"))

## Figure 6.5 / TS???




## Figure 8.1 /  TS8.1 / incomes & wages deciles / France
# remove years < 1910, which have many NAs: start rowIndex at 16
ts8.1 <- read.xlsx("../Piketty2014FiguresTables/Chapter8TablesFigures.xlsx",
  sheetName = "TS8.1", rowIndex = 16:116, colIndex = 1:6, header = FALSE)
names(ts8.1) <- c("Year", "top_10_is", "top_1_is", "top_0.1_is", "top_10_ws", "top_1_ws")
df8.1 <- ts8.1[, c("Year", "top_10_is", "top_10_ws")]
names(df8.1) <- c("Year", "Incomes", "Wages")
df8.1 <- melt(df8.1, id.vars = c("Year"))

## Figure 8.2 /  TS8.1 / incomes & wages percentiles / France
df8.2 <- ts8.1[, c("Year", "top_1_is", "top_1_ws")]
names(df8.2) <- c("Year", "Incomes", "Wages")
df8.2 <- melt(df8.2, id.vars = c("Year"))

## Figure 8.3 /  TS8.3 / income sources / France / 1932
ts8.3 <- read.xlsx("../Piketty2014FiguresTables/Chapter8TablesFigures.xlsx",
  sheetName = "TS8.3", rowIndex = c(6:11,15:20,24:29), colIndex = 1:7, header = FALSE)
names(ts8.3) <- c("Quantile", "Labor Income", "Capital Income", "Mixed Income", "Labor Income", "Capital Income", "Mixed Income")
ts8.3 <- rbind(ts8.3[,1:4], ts8.3[,c(1,5:7)])
ts8.3[c(1:6,19:24), "Country"] <- "France"
ts8.3[c(7:12,13:18,25:30,31:36), "Country"] <- "United States"
ts8.3[1:6, "Year"] <- "1932"
ts8.3[c(7:12,13:18), "Year"] <- "1929"
ts8.3[19:24, "Year"] <- "2005"
ts8.3[c(25:30,31:36), "Year"] <- "2007"
ts8.3[c(1:6,13:18,19:24,31:36), "Type"] <- "Excluding capital gains"
ts8.3[c(7:12,25:30), "Type"] <- "Including capital gains"
ts8.3[, c("Country","Year","Type")] <- lapply(ts8.3[, c("Country","Year","Type")] , factor)
df8.3 <- melt(ts8.3, id.vars = c("Quantile", "Country", "Year", "Type"))
df8.3 <- subset(df8.3, Country == "France" & Year == "1932" & Type == "Excluding capital gains")
df8.3 <- df8.3[, c("Quantile", "variable", "value")]

## Figure 8.4 /  TS8.3 / income by sources / France / 2005
df8.4 <- melt(ts8.3, id.vars = c("Quantile", "Country", "Year", "Type"))
df8.4 <- subset(df8.4, Country == "France" & Year == "2005" & Type == "Excluding capital gains")
df8.4 <- df8.4[, c("Quantile", "variable", "value")]

## Figure 8.5 /  TS8.2 / top decile w/o capital gains / USA
# remove years < 1910, which have many NAs: start rowIndex at 16
ts8.2 <- read.xlsx("../Piketty2014FiguresTables/Chapter8TablesFigures.xlsx",
  sheetName = "TS8.2", rowIndex = 16:116, colIndex = 1:11, header = FALSE)
names(ts8.2) <- c("Year",
  "top_10_is","top_10_5_is", "top_5_1_is","top_1_is", "top_0.1_is",
  "top_10_is_wok", "top_1_is_wok", "top_0.1_is_wok", 
  "top_10_ws", "top_1_ws")
  # is = income share
  # wok = without kapital gains
  # ws = wage share
df8.5 <- ts8.2[, c("Year", "top_10_is", "top_10_is_wok")]
names(df8.5) <- c("Year", "Including capital gains", "Excluding capital gains")
df8.5 <- melt(df8.5, id.vars = "Year")

## Figure 8.6 /  TS8.2 / incomes for 3 quantiles / USA
df8.6 <- ts8.2[, c("Year", "top_1_is", "top_5_1_is", "top_10_5_is")]
names(df8.6) <- c("Year", "Top 1% (above $352,000)", "Top 5%-1% (between $150,000 and $350,000)", "Top 10%-5% (between $108,000 and $150,000)")
df8.6 <- melt(df8.6, id.vars = "Year")

## Figure 8.7 /  TS8.2 / incomes & wages deciles / USA
df8.7 <- ts8.2[, c("Year", "top_10_is", "top_10_is_wok", "top_10_ws")]
names(df8.7) <- c("Year", "Incomes", "Incomes (Excluding capital gains)", "Wages")
df8.7 <- melt(df8.7, id.vars = c("Year"))

## Figure 8.8 /  TS8.2 / incomes & wages percentiles / USA
df8.8 <- ts8.2[, c("Year", "top_1_is", "top_1_is_wok", "top_1_ws")]
names(df8.8) <- c("Year", "Incomes", "Incomes (Excluding capital gains)", "Wages")
df8.8 <- melt(df8.8, id.vars = c("Year"))

## Figure 8.9 /  TS8.3 / income by sources / USA / 1929
df8.9 <- melt(ts8.3, id.vars = c("Quantile", "Country", "Year", "Type"))
df8.9 <- subset(df8.9, Country == "United States" & Year == "1929" & Type == "Including capital gains")
df8.9 <- df8.9[, c("Quantile", "variable", "value")]

## Figure 8.10 /  TS8.3 / income by sources / USA / 2007
df8.10 <- melt(ts8.3, id.vars = c("Quantile", "Country", "Year", "Type"))
df8.10 <- subset(df8.10, Country == "United States" & Year == "2007" & Type == "Including capital gains")
df8.10 <- df8.10[, c("Quantile", "variable", "value")]

## Figure 9.8 / TS8.1 + TS9.4 / top deciles / USA & Europe
# remove years < 1910, which have many NAs: start rowIndex at 16
# USA
df8.2b <- ts8.2[, c("Year", "top_10_is")]
names(df8.2b) <- c("Year", "United States")
# Europe
ts9.4 <- read.xlsx("../Piketty2014FiguresTables/Chapter9TablesFigures.xlsx",
  sheetName = "TS9.4", rowIndex = 16:116, colIndex = 1:3, header = FALSE)
names(ts9.4) <- c("Year", "Including Sweden", "Excluding Sweden")
df9.4b <- ts9.4[, c("Year", "Including Sweden")]
names(df9.4b) <- c("Year", "Europe")
df9.8 <- merge(df8.2b, df9.4b, by = c("Year"))
df9.8 <- melt(df9.8, id.vars = "Year")


## Figure 10.1 / TS???


## Figure 10.2 / TS???

## Figure 10.3 / TS???

## Figure 10.4 / TS???

## Figure 10.6 / TS???

## Figure 10.9 / TS???

## Figure 10.10 / TS???

## Figure 12.1 / TS???

## Figure 12.2 / TS???

## Figure 12.3 / TS???

## Figure 12.4 / TS???

## Figure 12.5 / TS???



## Figure 14.1 / TS14.1 / marginal income tax rates / 4 countries
ts14.1 = read.xlsx("../Piketty2014FiguresTables/Chapter14TablesFigures.xlsx", 
  sheetName = "TS14.1", rowIndex = 5:118, colIndex = c(1:5, 7:16), header = FALSE)
names(ts14.1) = c("Year", "United States", "United Kingdom", "Germany", "France", "United States (top marginal rate on earned income)", "United States (top effective rate)", "United Kingdom (top marginal rate on earned income)", "France (income tax)", "France (CSG)", "Japan (Saez-Moriguchi Table A0)")
df14.1 <- ts14.1[, c("Year", "United States", "United Kingdom", "Germany", "France")]
df14.1 <- melt(df14.1, id.vars = "Year")

## Figure 14.2 / TS14.2 / marginal inheritance tax rates / 4 countries
ts14.2 = read.xlsx("../Piketty2014FiguresTables/Chapter14TablesFigures.xlsx", 
  sheetName = "TS14.2", rowIndex = 5:118, colIndex = c(1:5), header = FALSE)
names(ts14.2) = c("Year", "United States", "United Kingdom", "Germany", "France")
df14.2 <- melt(ts14.2, id.vars = "Year")

@


%%%%%%%%%% Start of Document %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}

%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=TitlePage_1]
\maketitle% first slide with title/author information
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Introduction_1]
\frametitle{Presention layout}
\begin{itemize}
\item
This presentation is based upon Capital in the 21st century (Harvard University Press, March 2014)
\item
This book studies the global dynamics of income and wealth distribution since 18c in 20+ countries; I use historical data collected over the past 15 years with Atkinson, Saez, Postel-Vinay, Rosenthal, Alvaredo, Zucman, and 30+ others; I try to shift attention from rising income inequality to rising wealth inequality
\item
The book includes four parts:
\begin{itemize}
\item
Part 1. Income and capital
\item
Part 2. The dynamics of the capital/income ratio 
\item
Part 3. The structure of inequalities
\item
Part 4. Regulating capital in the 21st century
\end{itemize}
\item 
I will present some results from Parts 2 \& 3, focusing upon the long-run evolution of capital/income ratios and wealth concentration (\href{all graphs and series are available online}{http://piketty.pse.ens.fr/capital21c}.
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=WTID]
\frametitle{The World Top Incomes Database}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
\includegraphics[width=0.9\textwidth]
{pictures/WorldTopIncomesDatabase}
\caption{\textbf{\url{http://topincomes.parisschoolofeconomics.eu}}}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_0_1,fragile]
\frametitle{Figure I.1: Income inequality in the United States, 1910--2012}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.0.1', out.width='1\\linewidth'>>=
ggplot(data = df0.1, aes(x = Year, y = value)) + geom_line(colour = colorPalette[1]) + geom_point(shape = shapePalette[1], size = 3, colour = colorPalette[1]) + ylab("Share of top decile in national income") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1910, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(.3, .5, by = .05), limits = c(.3, .5))
@
\caption{The top decile share in U.S. national income dropped from 45--50\% in the 1910s--1920s to less than 35\% in the 1950s (this is the
1950 1960 fall documented by Kuznets); it then rose from less than 35\% in the 1970s to 45--50\% in the 2000s--2010s.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_0_2,fragile]
\frametitle{Figure I.2. The capital--income ratio in Europe, 1870--2012}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.0.2', out.width='1\\linewidth'>>=
ggplot(data = df0.2, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Market value of private capital (% national income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = pretty_breaks(n = 8)) + scale_y_continuous(labels = percent, breaks = seq(1, 8, by = 1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.6, .75), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) 
@
\caption{Aggregate private wealth was worth about 6--7 years of national income in Europe in 1910, between 2 and 3 years in 1950, and between 4 and 6 years in 2010.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_8_1,fragile]
\frametitle{Figure 8.1. Income inequality in France, 1910--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.8.1', out.width='1\\linewidth'>>=
ggplot(data = df8.1, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share of top decile in total (incomes or wages)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1910, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(.2, .5, by = .05), limits = c(.2, .5)) + scale_shape_manual(name = "Share of top decile in total", values = shapePalette) + scale_colour_manual(name = "Share of top decile in total", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.7, .85), legend.background = element_rect(colour = 'black')) 
@
\caption{Inequality of total income (labor and capital) has dropped in France during the twentieth century, while wage inequality has remained the same.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_8_2,fragile]
\frametitle{Figure 8.2. The fall of rentiers in France, 1910--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.8.2', out.width='1\\linewidth'>>=
ggplot(data = df8.2, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share of top decile in total (incomes or wages)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1910, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, .22, by = .02)) + scale_shape_manual(name = "Share of top percentile in total", values = shapePalette) + scale_colour_manual(name = "Share of top percentile in total", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.7, .85), legend.background = element_rect(colour = 'black')) 
@
\caption{The fall in the top percentile share (the top 1 percent highest incomes) in France between 1914 and 1945 is due to the fall of top capital incomes.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_8_3,fragile]
\frametitle{Figure 8.3. The composition of top incomes in France in 1932}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.8.3', out.width='1\\linewidth'>>=
ggplot(data = df8.3, aes(x = Quantile, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share in total income of various fractiles") + xlab("") + theme_bw() + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Type of income", values = shapePalette) + scale_colour_manual(name = "Type of income", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.5, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) 
@
\caption{Labor income becomes less and less important as one goes up within the top decile of total income. Notes: (i)~``P90--95'' includes individuals between percentiles 90 to 95, ``P95--99'' includes the next 4 percent, ``P99--99.5'' the next 0.5 percent, etc.; (ii)~Labor income: wages, bonuses, pensions. Capital income: dividends, interest, rent. Mixed income: self-employment income.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_8_4,fragile]
\frametitle{Figure 8.4. The composition of top incomes in France in 2005}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.8.4', out.width='1\\linewidth'>>=
ggplot(data = df8.4, aes(x = Quantile, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share in total income of various fractiles") + xlab("") + theme_bw() + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Type of income", values = shapePalette) + scale_colour_manual(name = "Type of income", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.5, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) 
@
\caption{Capital income becomes dominant at the level of the top 0.1 percent in France in 2005, as opposed to the top 0.5 percent in 1932.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_8_5,fragile]
\frametitle{Figure 8.5. Income inequality in the United States, 1910--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.8.5', out.width='1\\linewidth'>>=
ggplot(data = df8.5, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share of top decile in national income") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1910, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(.3, .5, by = .05), limits = c(.3, .5)) + scale_shape_manual(name = "Share of top decile in total income", values = shapePalette) + scale_colour_manual(name = "Share of top decile in total income", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.6, .85), legend.background = element_rect(colour = 'black')) 
@
\caption{The top decile share in U.S. national income dropped from 45--50\% in the 1910s--1920s to less than 35\% in the 1950s (this is the
1950 1960 fall documented by Kuznets); it then rose from less than 35\% in the 1970s to 45--50\% in the 2000s--2010s.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_8_6,fragile]
\frametitle{Figure 8.6. Decomposition of the top decile, United States, 1910--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.8.6', out.width='1\\linewidth'>>=
ggplot(data = df8.6, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share of the different groups in total income") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1910, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0.08, .24, by = .02), limits = c(.08, .25)) + scale_shape_manual(name = "Annual incomes in 2010", values = shapePalette) + scale_colour_manual(name = "Annual incomes in 2010", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.55, .85), legend.background = element_rect(colour = 'black')) 
@
\caption{The rise of the top decile income share since the 1970s is mostly due to the top percentile.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_8_7,fragile]
\frametitle{Figure 8.7. High incomes and high wages in the United States, 1910--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering % To Do: add 'excluding capital gains'
<<'Figure.8.7', out.width='1\\linewidth'>>=
ggplot(data = df8.7, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share of top decile in total (incomes or wages)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1910, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(.2, .5, by = .05)) + scale_shape_manual(name = "Share of top decile in total", values = shapePalette) + scale_colour_manual(name = "Share of top decile in total", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.55, .85), legend.background = element_rect(colour = 'black')) 
@
\caption{The rise of income inequality since the 1970s is largely due to the rise of wage inequality.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_8_8,fragile]
\frametitle{Figure 8.8. The transformation of the top 1 percent in the United States, 1910--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering % To Do: add 'excluding capital gains'
<<'Figure.8.8', out.width='1\\linewidth'>>=
ggplot(data = df8.8, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share of top decile in total (incomes or wages)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1910, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, .3, by = .02)) + scale_shape_manual(name = "Share of top percentile in total", values = shapePalette) + scale_colour_manual(name = "Share of top percentile in total", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.55, .85), legend.background = element_rect(colour = 'black')) 
@
\caption{The rise in the top 1 percent highest incomes since the 1970s is largely due to the rise in the top 1 percent highest wages.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_8_9,fragile]
\frametitle{Figure 8.9. The composition of top incomes in the United States in 1929}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.8.9', out.width='1\\linewidth'>>=
ggplot(data = df8.9, aes(x = Quantile, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share in total income of various fractiles") + xlab("") + theme_bw() + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Type of income", values = shapePalette) + scale_colour_manual(name = "Type of income", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.5, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) 
@
\caption{Labor income becomes less and less important as one moves up within the top income decile.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_8_10,fragile]
\frametitle{Figure 8.10. The composition of top incomes in the United States in 2007}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.8.10', out.width='1\\linewidth'>>=
ggplot(data = df8.10, aes(x = Quantile, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share in total income of various fractiles") + xlab("") + theme_bw() + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Type of income", values = shapePalette) + scale_colour_manual(name = "Type of income", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.5, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) 
@
\caption{Capital income becomes dominant at the level of top 0.1 percent in 2007, as opposed to the top 1 percent in 1929.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=ThreePoints,fragile,shrink=4]
\frametitle{This presentation: three points}
\begin{enumerate}
\item
\textbf{The return of a patrimonial (or wealth-based) society} in the Old World (Europe, Japan). Wealth-income ratios seem to be returning to very high levels in low growth countries.
\medskip\newline
Intuition: in a slow-growth society, wealth accumulated in the past can naturally become very important. In the very long run, this can be relevant for the entire world.
\item 
\textbf{The future of wealth concentration}: with high $r-g$ during 21c ($r =$~`net-of-tax rate of return', $g =$~`growth rate'), then wealth inequality might reach or surpass 19c oligarchic levels; conversely, suitable institutions can allow to democratize wealth.
\item
\textbf{Inequality in America} (``meritocratic extremism''): is the New World developing a new inequality model that is based upon extreme labor income inequality more than upon wealth inequality? Is it more merit-based, or can it become the worst of all worlds?
\end{enumerate}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=BrasilVersus]
\frametitle{Brasil vs Europe--US--Japan}
\begin{itemize}
\item
\textbf{Top income shares}: income inequality is known to be high in Brasil; but it is probably underestimated (problem with household surveys); little access to fiscal data in Brasil.
\item 
\textbf{Wealth-income ratios}: probably a strong rise in Brasil (real estate prices), but we do not really know.
\item
\textbf{Wealth inequality}: probably very high, but we do not really know; no access to property tax and inheritance tax statistics.
\item
\textbf{Like other countries, Brasil needs more transparency about income and wealth}; progressive tax on income, inheritance and wealth would be a powerful way to produce information about how the different income and wealth groups are benefiting from growth.
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=BrazilUSTop1]
\frametitle{Top 1\% income share: Brazil and United States, 2006--2012}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
\includegraphics[width=\textwidth]
{pictures/Top1BrazilVsUSA}
\caption{To Do: Get Data to Recreate Figure}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=BrazilUSTop10]
\frametitle{Top 10\% income share: Brazil and United States, 2006--2012}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
\includegraphics[width=\textwidth]
{pictures/Top10BrazilVsUSA}
\caption{To Do: Get Data to Recreate Figure}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=BrazilInequality]
\frametitle{Income Inequality in Brazil: 1976--2013}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
\includegraphics[width=\textwidth]
{pictures/IncomeInequalityBrazil}
\caption{To Do: Get Data to Recreate Figure}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\againframe[shrink=4]{ThreePoints}

\againframe{Figure_0_2}

%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_5_1]
\frametitle{Figure 5.1: Private \& public capital in Europe \& United States, 1870--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.5.1', out.width='1\\linewidth'>>=
ggplot(data = df5.1, aes(x = Year, y = value, group = interaction(variable,Type), shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Value of capital (% national income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1870, 2010, by = 20)) + scale_y_continuous(labels = percent, breaks = seq(-1, 8, by = 1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.6, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) 
@
\caption{The fluctuations of national capital in the long run correspond mostly to the fluctuations of private capital (both in Europe and in the United States).}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_5_2]
\frametitle{Figure 5.2: National capital in Europe \& United States, 1870--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.5.2', out.width='1\\linewidth'>>=
ggplot(data = df5.2, aes(x = Year, y = value, group = interaction(variable,Type), shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Value of capital (% national income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1870, 2010, by = 20)) + scale_y_continuous(labels = percent, breaks = seq(-1, 8, by = 1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.6, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) 
@
\caption{National capital (public and private) is worth 6.5 years of national income in Europe in 1910, versus 4.5 years in the United States.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_5_3]
\frametitle{Figure 5.3: Private capital in rich countries, 1970--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.5.3', out.width='1\\linewidth'>>=
# Spain included, to remove replace df with df[df['variable'] != "Spain",]
ggplot(data = df5.3, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Value of private capital (% national income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1970, 2010, by = 5)) + scale_y_continuous(limits = c(2, 9), labels = percent, breaks = seq(2, 8, by = 1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.28, .87), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) + guides(shape = guide_legend(ncol = 3)) 
@
\caption{Private capital is worth between 2 and 3.5 years of national income in rich countries in 1970, and between 4 and 7 years of national income in 2010.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_5_3b]
\frametitle{Figure 5.3b: Public capital in rich countries, 1970--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.5.3b', out.width='1\\linewidth'>>=
ggplot(data = df5.3b, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Value of public capital (% national income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1970, 2010, by = 5)) + scale_y_continuous(limits = c(-1, 1.25), labels = percent, breaks = seq(-.75, 1.25, by = .25)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.25, .15), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) + guides(shape = guide_legend(ncol = 3)) 
@
\caption{In France, Britain, Germany, and the United States, government deficits exceeded public investment by 2--3\% of national income on average over the period 1970--2010, compared with more than 6\% in Italy.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_5_4]
\frametitle{Figure 5.4: Private capital in rich countries (ratio), 1970--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.5.4', out.width='1\\linewidth'>>=
# Spain included, to remove replace df with df[df['variable'] != "Spain",]
ggplot(data = df5.4, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Private capital (% disposable household income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1970, 2010, by = 5)) + scale_y_continuous(labels = percent, breaks = seq(3, 10, by = 1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.22, .8), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) + guides(shape = guide_legend(ncol = 2)) 
@
\caption{Expressed in years of household disposable income (about 70--80\% of national income), the capital/income ratio appears to be larger than when it is expressed in years of national income.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_5_5]
\frametitle{Figure 5.5: Private and public capital in rich countries, 1970--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.5.5', out.width='1\\linewidth'>>= ## out.height='0.75\\textheight'
ggplot(data = df5.5, aes(x = Year, y = value, group = interaction(variable,Type), shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Value of capital (% national income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1970, 2010, by = 5)) + scale_y_continuous(limits = c(-1, 10), labels = percent, breaks = seq(-1, 9, by = 1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.25, .8), legend.background = element_rect(colour = 'black'), legend.title = element_blank(), legend.title = element_blank()) + guides(shape = guide_legend(ncol = 2)) 
@
\caption{In Italy, private capital rose from 240\% to 680\% in national income between 1970 and 2010, while public capital dropped from 20\% to -70\%.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_5_6]
\frametitle{Figure 5.6: Market value and book value of corporations, 1970--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.5.6', out.width='1\\linewidth'>>=
ggplot(data = df5.6, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("ratio between market value and book value of corporations") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1970, 2010, by = 5)) + scale_y_continuous(labels = percent, breaks = seq(0, 1.6, by = .2)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.25, .8), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) + guides(shape = guide_legend(ncol = 2)) 
@
\caption{Tobin's Q (i.e. the ratio between market value and book value of corporations) has risen in rich countries since the 1970s--1980s.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_5_7]
\frametitle{Figure 5.7: National capital in rich countries, 1970--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.5.7', out.width='1\\linewidth'>>=  ##out.height='0.75\\textheight'
ggplot(data = df5.7, aes(x = Year, y = value, group = interaction(variable,Type), shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Value of capital (% national income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1970, 2010, by = 5)) + scale_y_continuous(limits = c(-1, 10), labels = percent, breaks = seq(-1, 10, by = 1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.22, .8), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) + guides(shape = guide_legend(ncol = 2)) 
@
\caption{Net foreign assets held by Japan and Germany are worth between 6 months and one year of national income in 2010.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_5_8]
\frametitle{Figure 5.8: The world capital/income ratio, 1870--2100}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.5.8', out.width='1\\linewidth'>>=
ggplot(data = df5.8, aes(x = Year, y = value, colour = Type)) + geom_line() + geom_point(aes(colour = Type, shape = Type), size = 3) + ylab("Value of capital (% national income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1870, 2100, by = 20)) + scale_y_continuous(labels = percent, breaks = seq(2.5, 7, by = .5)) + scale_linetype_manual(name = "World capital/income ratio", values = linePalette) + scale_shape_manual(name = "World capital/income ratio", values = shapePalette) + scale_colour_manual(name = "World capital/income ratio", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.5, .8), legend.background = element_rect(colour = 'black')) 
@
\caption{According to simulations (central scenario), the world capital/income ratio could be close to 700 percent by the end of the twenty-first century.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Table_12_1]
\frametitle{Table 12.1: The growth rate of top global wealth, 1987--2013}
\begin{table}[t]
%\caption{The growth rate of top global wealth, 1987--2013}
\adjustbox{max height=\dimexpr\textheight-5.5cm\relax,
           max width=\textwidth}{%
\begin{threeparttable}
\centering
\begin{tabular}{@{}lc@{}}
\toprule
    & Average real growth rate per year  \\
    & (after deduction of inflation) (\%) \\
\midrule
    The top 1/(100 million) highest wealth holders \tnote{a}   & 6.8  \\
    The top 1/(20 million)  highest wealth holders \tnote{b}   & 6.4  \\
    Average world wealth per adult                             & 2.1  \\
    Average world income per adult                             & 1.4  \\
    World adult population                                     & 1.9  \\
    World GDP                                                  & 3.3  \\
\midrule
\end{tabular}
\begin{tablenotes}
    \item Between 1987 and 2013, the highest global wealth fractiles have grown at 6--7\% per year versus 2.1\% for average world wealth, and 1.4\% for average world income. All growth rates are net of inflation (2.3\% per year between 1987 and 2013).
    \item[a] About 30 adults out of 3 billion in the 1980s, and 45 adults out of 4.5 billion in 2010.
    \item[b] About 150 adults out of 3 billion in the 1980s, and 225 adults out of 4.5 billion in the 2010s.
\end{tablenotes}
\end{threeparttable}}
\end{table}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Table_12_2]
\frametitle{Table 12.2: The return on the capital endowments of U.S. universities, 1980--2010}
\begin{table}[t]
%\caption{The return on the capital endowments of U.S. universities, 1980--2010}
\adjustbox{max height=\dimexpr\textheight-5.5cm\relax,
           max width=\textwidth}{%
\begin{threeparttable}
\centering
\begin{tabular}{@{}lc@{}}
\toprule
    & Average real annual rate of return                           \\
    & (after deduction of inflation and all                        \\
    & administrative costs and financial fees) (\%)                \\
\midrule
    All universities (850)                                & 8.2    \\
    Harvard, Yale, and Princeton                          & 10.2   \\
    Endowments higher than \$1 billion (60)               & 8.8    \\
    Endowments between \$500 million and 1 billion (66)   & 7.8    \\
    Endowments between \$100 and \$500 million (226)      & 7.1    \\
    Endowments less than \$100 million (498)              & 6.2    \\
\midrule
\end{tabular}
\begin{tablenotes}
    \item Between 1980 and 2010, U.S. universities earned an average real rate of return of 8.2\% on their capital endowments, and more for the greater endowments. All returns are reported net of inflation (2.4\% per year between 1980 and 2010) and net of administrative costs and financial fees.
\end{tablenotes}
\end{threeparttable}}
\end{table}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_9_8]
\frametitle{Figure 9.8: Income inequality: Europe vs. United States, 1900--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.9.8', out.width='1\\linewidth'>>=
ggplot(data = df9.8, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Share of top decile in national income") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(.25, .5, by = .05)) + scale_shape_manual(name = "Share of top decile \n in national income", values = shapePalette[1:2]) + scale_colour_manual(name = "Share of top decile \n in national income", values = colorPalette[1:2]) + theme(legend.key = element_blank(), legend.position = c(.6, .85), legend.background = element_rect(colour = 'black')) 
@
\caption{The top decile income share was higher in Europe than in the U.S. in 1900--2010. It is much higher in the U.S. in 2000--2010.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_14_1]
\frametitle{Figure 14.1: Top income tax rates, 1900--2013}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.14.1', out.width='1\\linewidth'>>=
ggplot(data = df14.1, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest incomes") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.55, .15), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) + guides(shape = guide_legend(ncol = 2)) 
@
\caption{The top marginal tax rate of the income tax (applying to the highest incomes) in the U.S. dropped from 70\% in 1980 to 28\% in 1988.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_14_2]
\frametitle{Figure 14.2: Top inheritance tax rates, 1900--2013}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.14.2', out.width='1\\linewidth'>>=
ggplot(data = df14.2, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(limits = c(0, 1), labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.2, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{The top marginal tax rate of the inheritance tax (applying to the highest inheritances) in the U.S. dropped from 70\% in 1980 to 35\% in 2013.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Conclusions_1,shrink=7]
\frametitle{Conclusions}
\begin{itemize}
\item
\textbf{The history of income and wealth inequality is always political, chaotic and unpredictable; it involves national identities and sharp reversals; nobody can predict the reversals of the future.}
\item
Marx: with $g=0$, $\beta \to \infty$, $r \to 0$ : revolution, war
\item
My conclusions are less apocalyptic: with $g>0$, at least we have a steady state $\beta = s/g$.
\item
But with $g>0$ \& small, this steady-state can be rather gloomy: it can involve a very large capital-income ratio $\beta$ and capital share $\alpha$, as well as extreme wealth concentration due to high $r-g$.
\item
This has nothing to do with a market imperfection: the more perfect the capital market, the higher $r-g$.
\item
The ideal solution: progressive wealth tax at the global scale, based upon automatic exchange of bank information.
\item
Other solutions involve authoritarian political \& capital controls (China, Russia..), or perpetual population growth (US), or inflation, or some mixture of all.
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Transition_1]
\begin{center}
\begin{huge}
Supplementary Slides
\vspace{3\baselineskip}\par
(long lecture version)
\end{huge}
\end{center}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% Long Version Starts Here


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=WealthReturn,shrink=8]
\frametitle{1. The return of a wealth-based society}
\begin{itemize}
\item
Wealth = capital $K$ = everything we own and that can be sold on a market (net of all debts) (excludes human $K$, except in slave societies)
\item
In textbooks, wealth-income \& capital-ouput ratios are supposed to be constant. But the so-called ``Kaldor facts'' actually rely on little historical evidence.
\item
In fact, we observe in Europe \& Japan a large recovery of $\beta=K/Y$ in recent decades:
\begin{align*}
\beta = 200-300\% ~\text{in}~ 1950-1960 \\
\beta = 500-600\% ~\text{in}~ 2000-2010
\end{align*}
\begin{footnotesize}
(i.e. average wealth $K$ was about 2--3 years of average income $Y$ around 1950--1960; it is about 5--6 years in 2000--2010)
\linebreak
(with $\beta \simeq 600\%$, if $Y \simeq \euro 30,000$ per capita, then $K \simeq \euro 180,000$ per capita) (currently, $K \simeq$ half real estate, half financial assets)
\end{footnotesize}
\item
\textbf{Are we heading back to the $\beta = 600-700\%$ observed in the wealth-based societies of 18c-19c? Or even more?}
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\againframe{Figure_5_3}


\againframe{Figure_5_5}


\againframe{Figure_5_7}


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_3_1]
\frametitle{Figure 3.1: Capital in Britain, 1700--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.3.1', out.width='1\\linewidth'>>=
#ggplot(data = df3.1, aes(x = Year, y = value, group = variable, fill = variable)) + geom_area(position = 'stack', colour = gray, alpha = .5, show_guide = TRUE) + ylab("Value of national capital(% of national income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1700, 2010, by = 25)) + scale_y_continuous(labels = percent, breaks = seq(0, 8, by = 1)) + scale_fill_brewer(palette = "Blues") + theme(legend.key = element_blank(), legend.position = "right", legend.background = element_rect(colour = 'black'), legend.title = element_blank()) + guides(shape = guide_legend(ncol = 1), fill = guide_legend(reverse = TRUE))
@
\caption{National capital is worth about seven years of national income in Britain in 1700 (including four in agricultural land).}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_3_2]
\frametitle{Figure 3.2: Capital in France, 1700--2010}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.3.2', out.width='1\\linewidth'>>=
#ggplot(data = df3.2, aes(x = Year, y = value, group = variable, fill = variable)) + geom_area(position = 'stack', colour = gray, alpha = .5, show_guide = TRUE) + ylab("Value of national capital(% of national income)") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1700, 2010, by = 25)) + scale_y_continuous(labels = percent, breaks = seq(0, 8, by = 1)) + scale_fill_brewer(palette = "Blues") + theme(legend.key = element_blank(), legend.position = "right", legend.background = element_rect(colour = 'black'), legend.title = element_blank()) + guides(shape = guide_legend(ncol = 1), fill = guide_legend(reverse = TRUE))
@
\caption{National capital is worth almost seven years of national income in France in 1910 (including one invested abroad).}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=CapitalIsBack]
\frametitle{Capital is back}
\begin{itemize}
\item
The simplest way to think about this is the following: 
\begin{itemize}
\item
In the long-run, $\beta = s/g$
\par\medskip
with $s$ = (net-of-depreciation) saving rate and $g$ = economy's growth rate (population + productivity).
\end{itemize}
\item
With $s = 10\%$, $g = 3\%$, $\beta \simeq 300\%$; but if $s = 10\%$, $g = 1.5\%$, $\beta \simeq 600\%$.
\item
\textbf{In slow-growth societies, the total stock of wealth accumulated in the past can naturally be very important.}
\item
$\rightarrow$ \textbf{capital is back because low growth is back.}
(in particular because population growth $\downarrow 0$)
\item
$\rightarrow$ \textbf{in the long run, this can be relevant for the entire planet.}
\item
Note: $\beta = s/g$ = pure stock-flow accounting identity; it is true whatever the combination of saving motives.
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_12_5]
\frametitle{Figure 12.5: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.12.5', out.width='1\\linewidth'>>=
#ggplot(data = df12.5, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=ElasticityKL,shrink=14]
\frametitle{The capital--labor elasticity of substitution}
\begin{itemize}
\item
\textbf{Will the rise of capital income-ratio $\beta$ also lead to a rise of the capital share $\alpha$ in national income?}
\item
If the capital stock equals $\beta = 6$ years of income and the average return to capital is equal $r = 5\%$ per year, then the share of capital income (rent, dividends, interest, profits, etc.) in national income equals $\alpha = r \times \beta = 30\%$.
\item
Technically, whether a rise in $\beta$ also leads to a rise in capital share $\alpha = r \beta$ depends on the elasticity of substitution $\sigma$ between capital $K$ and labor $L$ in the production function $Y = F(K, L)$.
\item
Intuition: $\sigma$ measures the extent to which workers can be replaced by machines (e.g. Amazon’s drones).
\item
Standard assumption: Cobb-Douglas production function ($\sigma = 1$) = as the stock $\beta \uparrow$, the return $r \downarrow$ exactly in the same proportions, so that $\alpha = r \times \beta$ remains unchanged, like by magic = a stable world where the capital--labor split is entirely set by technology.
\item
But if $\sigma > 1$, then the return to capital $r \downarrow$ falls less than the volume of capital $\beta\uparrow$, so that the product $\alpha = r \times \beta \uparrow$.
\item
\textbf{Exactly what happened since the 1970s--80s: both the ratio $\beta$ and the capital share $\alpha$ have increased.}
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_6_5]
\frametitle{Figure 6.5: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.6.5', out.width='1\\linewidth'>>=
#ggplot(data = df6.5, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Robots]
\frametitle{Towards a world of robots?}
\begin{itemize}
\item
With a large rise in $\beta$, one can get large rise in $\alpha$ with a production function $F(K,L)$ that is just a little bit more substituable than in the standard Cobb-Douglas model (say if $\sigma = 1.5$ instead of $1$).
\item
Maybe it is natural to expect $\sigma \uparrow$ over the course of history: more and more diversified uses for capital;
\textbf{extreme case: pure robot-economy} ($\sigma = $ infinity).
\item
Less extreme case: there are many possible uses for capital (machines can replace cashiers, drones can replace Amazon's delivery workers, etc.), so that the capital share $\alpha \uparrow$ continuously; there's no natural corrective mechanism for this.
\item
The rise of $\beta$ and $\alpha$ can be a good thing (we could all devote more time to culture, education, health..., rather than to our own subsistance), assuming one can answer the following question: \textbf{who owns the robots?}
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=WealthFuture]
\frametitle{2. The future of wealth concentration}
\begin{itemize}
\item
In all European countries (UK, France, Sweden...), wealth concentration was extremely high in 18c-19c \& until WW1:
\begin{itemize}
\item
about 90\% of aggregate wealth for top 10\% wealth holders
\item
about 60\% of aggregate wealth for top 1\% wealth-holders
\end{itemize}
\item
\textbf{= the classic patrimonial (wealth-based) society}: 
\begin{itemize}
\item
a minority lives off its wealth, while the rest of the populaton works (Austen, Balzac)
\end{itemize}
\item
Today wealth concentration is still very high, but less extreme:\hfill
\begin{itemize}%\vspace{-\baselineskip}% hack
\item
about 60--70\% for top 10\%; about 20--30\% for top 1\%
\item
the bottom 50\% still owns almost nothing (<5\%)
\item
but the middle 40\% now owns 20--30\% of aggregate wealth
\item
\textbf{= the rise of a patrimonial middle class}.
\end{itemize}
\item
\textbf{How did it happen, and will it last? Will the patrimonial middle class expend, or will it shrink?}
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_10_1]
\frametitle{Figure 10.1: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.10.1', out.width='1\\linewidth'>>=
#ggplot(data = df10.1, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_10_2]
\frametitle{Figure 10.2: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.10.2', out.width='1\\linewidth'>>=
#ggplot(data = df10.2, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_10_3]
\frametitle{Figure 10.3: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.10.3', out.width='1\\linewidth'>>=
#ggplot(data = df10.3, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_10_4]
\frametitle{Figure 10.4: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.10.4', out.width='1\\linewidth'>>=
#ggplot(data = df10.4, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=WealthShocks]
\frametitle{Wealth shocks}
\begin{itemize}
\item
\textbf{Key finding: there was no decline in wealth concentration prior to World War shocks; was it just due to shocks?}
\begin{itemize}
\item
\textbf{Question}: Apart from shocks, what forces determine the long-run level of wealth concentration?
\item
\textbf{Answer}: In any dynamic, multiplicative wealth accumulation model with random individual shocks (tastes, demographics, returns, wages,..), 
\textbf{the steady-state level of wealth concentration is an increasing function of $r-g$}. 
\smallskip\par (with $r$ = net-of-tax rate of return and $g$ = growth rate)
\end{itemize}
\item
With growth slowdown and rising tax competition to attract capital, $r-g$ might well rise in the 21c $\rightarrow$ back to 19c levels.
\item
Future values of $r$ also depend on technology ($\sigma > 1$?)
\item 
Under plausible assumptions, wealth concentration might reach or surpass 19c record levels: see global wealth rankings
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_10_9]
\frametitle{Figure 10.9: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.10.9', out.width='1\\linewidth'>>=
#ggplot(data = df10.9, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_10_10]
\frametitle{Figure 10.10: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.10.10', out.width='1\\linewidth'>>=
#ggplot(data = df10.10, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_2_1]
\frametitle{Figure 2.1: The growth of world population, 1700--2012}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.2.1', out.width='1\\linewidth'>>=
ggplot(data = df2.1, aes(x = Year, y = value, group = variable, fill = variable)) + geom_area(position = 'stack', colour = gray, alpha = .4, show_guide = FALSE) + ylab("World population (millions inhabitants)") + xlab("") + theme_bw() + scale_x_continuous(limits = c(1700, 2050), breaks = seq(1700, 2012, by = 50)) + scale_y_continuous(labels = comma, breaks = seq(0, 7000, by = 1000)) + scale_fill_brewer(palette = "Blues") + geom_text(data = subset(df2.1, Year == tail(df2.1$Year, 1)), aes(x = Year, y = cumsum(value), label = variable), vjust = 3, hjust = -.2, size = 4)
@
\caption{World population rose from 600 million inhabitants in 1700 to 7 billion in 2012.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_2_1_b]
\frametitle{Figure 2.1: The growth of world population, 1700--2012}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.2.1.b', out.width='1\\linewidth'>>=
ggplot(data = df2.1, aes(x = Year, y = value, group = variable, fill = variable)) + geom_area(position = 'stack', colour = gray, alpha = .5, show_guide = TRUE) + ylab("World population (millions inhabitants)") + xlab("") + theme_bw() + scale_x_continuous(limits = c(1700, 2012), breaks = seq(1700, 2012, by = 50)) + scale_y_continuous(labels = comma, breaks = seq(0, 7000, by = 1000)) + scale_fill_brewer(palette = "Blues") + theme(legend.key = element_blank(), legend.position = "right", legend.background = element_rect(colour = 'black'), legend.title = element_blank()) + guides(shape = guide_legend(ncol = 1), fill = guide_legend(reverse = TRUE))
@
\caption{World population rose from 600 million inhabitants in 1700 to 7 billion in 2012.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_2_2a]
\frametitle{Figure 2.2a: The growth rate of population from Antiquity to 2100}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.2.2a', out.width='1\\linewidth'>>=
ggplot(data = df2.2a, aes(x = Period, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Population growth rate") + xlab("") + theme_bw() + scale_y_continuous(limits = c(0, 0.02), labels = percent, breaks = seq(0, .02, by = .002)) + scale_shape_manual(name = "Continent", values = shapePalette) + scale_colour_manual(name = "Continent", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .75), legend.background = element_rect(colour = 'black'), legend.title = element_blank())
@
%\caption{}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_2_2]
\frametitle{Figure 2.2: The growth rate of world population from Antiquity to 2100}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.2.2', out.width='1\\linewidth'>>=
ggplot(data = df2.2, aes(x = Period, y = value, group = Type, colour = Type, shape = Type)) + geom_line() + geom_point(aes(colour = Type, shape = Type), size = 3) + ylab("World population growth rate") + xlab("") + theme_bw() + scale_y_continuous(limits = c(0, 0.02), labels = percent, breaks = seq(0, .02, by = .002)) + scale_shape_manual(name = "Continent", values = shapePalette) + scale_colour_manual(name = "Continent", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.25, .85), legend.background = element_rect(colour = 'black')) + guides(colour = guide_legend(title = NULL), shape = guide_legend(title = NULL))
@
\caption{The growth rate of world population was above 1 percent per year from 1950 to 2012 and should return toward 0 percent by the end of the twenty-first century.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_2_3]
\frametitle{Figure 2.3: The growth rate of per capita output since the Industrial Revolution}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.2.3', out.width='1\\linewidth'>>=
ggplot(data = df2.3, aes(x = Period, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(group = variable, shape = variable, colour = variable), size = 3) + ylab("Growth rate of per capita GDP") + xlab("") + theme_bw() + scale_y_continuous(limits = c(0, .05), labels = percent, breaks = seq(0, .05, by = .005)) + scale_shape_manual(name = "Continent", values = shapePalette) + scale_colour_manual(name = "Continent", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.25, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) 
@
\caption{The growth rate of per capita output surpassed 4 percent per year in Europe between 1950 and 1970, before returning to American levels.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_2_4]
\frametitle{Figure 2.4: The growth rate of world per capita output from Antiquity to 2100}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.2.4', out.width='1\\linewidth'>>=
ggplot(data = df2.4, aes(x = Period, y = value, group = Type, colour = Type, shape = Type)) + geom_line() + geom_point(aes(colour = Type, shape = Type), size = 3) + ylab("World population growth rate") + xlab("") + theme_bw() + scale_y_continuous(limits = c(-0.001, 0.03), labels = percent, breaks = seq(0, .03, by = .01)) + scale_shape_manual(name = "Continent", values = shapePalette) + scale_colour_manual(name = "Continent", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.25, .85), legend.background = element_rect(colour = 'black')) + guides(colour = guide_legend(title = NULL), shape = guide_legend(title = NULL))
@
\caption{The growth rate of per capita output surpassed 2 percent from 1950 to 2012. If the convergence process goes on, it will surpass 2.5 percent from 2012 to 2050, and then will drop below 1.5 percent.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_2_5]
\frametitle{Figure 2.5: The growth rate of world output from Antiquity to 2100}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.2.5', out.width='1\\linewidth'>>=
ggplot(data = df2.5, aes(x = Period, y = value, group = Type, colour = Type, shape = Type)) + geom_line() + geom_point(aes(colour = Type, shape = Type), size = 3) + ylab("World population growth rate") + xlab("") + theme_bw() + scale_y_continuous(limits = c(0, 0.045), labels = percent, breaks = seq(0, .05, by = .01)) + scale_shape_manual(name = "Continent", values = shapePalette) + scale_colour_manual(name = "Continent", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.25, .85), legend.background = element_rect(colour = 'black')) + guides(colour = guide_legend(title = NULL), shape = guide_legend(title = NULL))
@
\caption{The growth rate of world output surpassed 4 percent from 1950 to 1990. If the convergence process goes on, it will drop below 2 percent by 2050.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_2_6,fragile]
\frametitle{Figure 2.6. Inflation since the Industrial Revolution}
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.2.6', out.width='1\\linewidth'>>=
ggplot(data = df2.6, aes(x = Period, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Inflation rate (consumer price index)") + xlab("") + theme_bw() + scale_y_continuous(limits = c(-.02, .2), labels = percent, breaks = seq(-.02, .2, by = .02)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.25, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank()) 
@
\caption{Inflation in the rich countries was zero in the eighteenth and nineteenth centuries, high in the twentieth century, and roughly 2 percent a year since 1990.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_12_1]
\frametitle{Figure 12.1: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.12.1', out.width='1\\linewidth'>>=
#ggplot(data = df12.1, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_12_2]
\frametitle{Figure 12.2: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.12.2', out.width='1\\linewidth'>>=
#ggplot(data = df12.2, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_12_3]
\frametitle{Figure 12.3: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.12.3', out.width='1\\linewidth'>>=
#ggplot(data = df12.3, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\againframe{Table_12_1}


\againframe{Table_12_2}


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=InequalityUSA]
\frametitle{3. Inequality in America}
\framesubtitle{``meritocratic extremism''}
\begin{itemize}
\item
Inequality in America = a different structure as in Europe: 
\textbf{more egalitarian in some ways, more inegalitarian in some other dimensions}.
\item
The New World in the 19th century: the land of opportunity (capital accumulated in the past mattered much less than in Europe; perpetual demographic growth as a way to reduce the level of inherited wealth and wealth concentration)... and also the land of slavery.
\item 
Northern US were in many ways more egalitarian than Old Europe; but Southern US were more inegalitarian.
\item 
We still have the same ambiguous relationship of America with inequality today: in some ways more merit-based; in other ways more violent (prisons).
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%\againframe{Figure_3_2}


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_4_6]
\frametitle{Figure 4.6: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.4.6', out.width='1\\linewidth'>>=
#ggplot(data = df4.6, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\againframe{Figure_5_2}


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_4_10]
\frametitle{Figure 4.10: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.4.10', out.width='1\\linewidth'>>=
#ggplot(data = df4.10, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_4_11]
\frametitle{Figure 4.11: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.4.11', out.width='1\\linewidth'>>=
#ggplot(data = df4.11, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=USAvEU]
\frametitle{America Versus Europe}
\begin{itemize}
\item
The US distribution of income has become more unequal than in Europe over the course of the 20th century; it is now as unequal as pre--WW1 Europe.
\item 
But the structure of inequality is different: US 2013 has less wealth inequality than Europe 1913, but higher inequality of labor income.
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=Figure_10_6]
\frametitle{Figure 10.6: }
\begin{figure}[t]
\begin{minipage}[b]{\textwidth}
\centering
<<'Figure.10.6', out.width='1\\linewidth'>>=
#ggplot(data = df10.6, aes(x = Year, y = value, group = variable, shape = variable, colour = variable)) + geom_line() + geom_point(aes(shape = variable, colour = variable), size = 3) + ylab("Marginal tax rate applying to the highest inheritances") + xlab("") + theme_bw() + scale_x_continuous(breaks = seq(1900, 2010, by = 10)) + scale_y_continuous(labels = percent, breaks = seq(0, 1, by = .1)) + scale_shape_manual(name = "Country", values = shapePalette) + scale_colour_manual(name = "Country", values = colorPalette) + theme(legend.key = element_blank(), legend.position = c(.15, .85), legend.background = element_rect(colour = 'black'), legend.title = element_blank())  + guides(shape = guide_legend(ncol = 2)) 
@
\caption{.}
\end{minipage}
\end{figure}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\againframe{Figure_8_5}


\againframe{Figure_9_8}


%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[label=MeritVNorms]
\frametitle{Merit or Social Norms?}
\begin{itemize}
\item
Higher inequality of labor income in the US could reflect higher inequality in education investment; but it also reflects a huge rise of top executive compensation that it very hard to explain with education and productivity reasoning alone.
\item 
In the US, this is sometime described as more merit--based: the rise of top labor incomes makes it possible to become rich with no inheritance ($\simeq$~Napoleonic «préfets»)
\item 
\textbf{Problem: this can be the worst of all worlds for those who are neither top income earners nor top successors}: they are poor, and they are depicted as dump \& undeserving (by contrast, nobody was trying to depict Ancien Regime inequality as fair!).
\item 
It is unclear whether rise of top incomes has a lot to do with merit or productivity: sharp decline in top tax rates \& rise of CEO bargaining power are more convincing explanations; chaotic US history of social norms regarding inequality.
\end{itemize}
\end{frame}
%%%%%%%%%%%%%%%%%%%% Frame Here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\againframe{Figure_14_1}


\againframe{Figure_14_2}


\againframe[shrink=7]{Conclusions_1}



\end{document}

