Chapter 11: Merit and Inheritance in the Long Run
=================================================

### Data provenance

The data were downloaded as Excel files from: http://piketty.pse.ens.fr/en/capital21c2

### Loading relevant libraries and data

This document depends on the [xlsx](http://cran.r-project.org/web/packages/xlsx/index.html), [reshape2](http://cran.r-project.org/web/packages/reshape2/index.html), [scales](http://cran.r-project.org/web/packages/scales/index.html), [plyr](http://cran.r-project.org/web/packages/ggplot2/index.html) packages.


```{r loadCh0,message=FALSE}
library(ggplot2)
library(xlsx)
library(reshape2)
library(scales)
```

## Figures 11.1 - 11.12 The age-wealth profile in France

All figures from Table T11.1

```{r tableT11.1, message=FALSE, cache=TRUE, warning=FALSE}
table.ts11 <- read.xlsx("../Piketty2014FiguresTables//Chapter11TablesFigures.xlsx", sheetName="TS11.1", rowIndex=8:39, colIndex=c(1:13, 16:24), header=FALSE)
names(table.ts11) <- c("year", "Economic flow", "Fiscal flow",
                       "disp_income_econ", "disp_income_fiscal", 
                       "Adult Mortality", "Average death age", 
                       "Average age inheritors", "μ ratio Avg wealth",
                       "μ ratio corrected", "Annual inheritance flows",
                       "Simulated inheritance 1", "Simulated inheritance 2",
                       "Inheritance share Scenario 1", "Inheritance % labor resources Scenario 1",
                       "Living standard top 1% inheritance Scenario 1",
                       "Living standard top 1% labor earners Scenario 1",
                       "Cohort fraction Scenario 1",
                        "Inheritance share Scenario 2", "Inheritance % labor resources Scenario 2",
                       "Living standard top 1% inheritance Scenario 2",
                       "Cohort fraction Scenario 2")
table.ts11.melted <- melt(table.ts11, id.var="year")

qplot(year, value, data=subset(table.ts11.melted, variable %in% c("Economic flow", "Fiscal flow")), geom=c("line", "point"), color=variable, xlab="Year",
      ylab="Annual value of inheritance and gifts (% national income)") + xlim(1820, 2020) +
  ggtitle("Figure 11.1. The annual inheritance flow as a fraction of national income, France 1820-2010")

qplot(year, value * 100, data=subset(table.ts11.melted, variable == "Adult Mortality"), geom=c("line", "point"), color=variable, xlab = "The mortality rate fell in France during the 20th century (rise of life expectancy), \n and should increase somewhat during the 21st century (baby-boom effect). ", ylab= "Adult mortality rate (%)") + xlim(1820,2100) +
  theme(legend.position=c(0.6, 0.8), legend.background = element_rect(fill="transparent"))

qplot(year, value, data=subset(table.ts11.melted, variable %in% c("Average death age", "Average age inheritors")), geom=c("line", "point"), color=variable, xlab = "Year", ylab= "Average age in years") +
  xlim(1820,2100) +
  theme(legend.position=c(0.2, 0.8), legend.background = element_rect(fill="transparent")) +
  ggtitle("Figure 11.3. Average age of decedents and inheritors, France 1820-2100")

qplot(year, value * 100, data=subset(table.ts11.melted, variable %in% c("Annual inheritance flows", "Adult Mortality")), geom=c("line", "point"), color=variable, xlab = "Year", ylab= "Annual rate of transmission or mortality (%)
") +
  xlim(1820,2010) +
  theme(legend.position=c(0.7, 0.8), legend.background = element_rect(fill="transparent"))

qplot(year, value * 100, data=subset(table.ts11.melted, variable %in% 
                                c("μ ratio Avg wealth", "μ ratio corrected")), geom=c("line", "point"), color=variable, xlab = "Year", ylab= "Ratio between the average wealth of decedents and the living") + xlim(1820,2010) +
  theme(legend.position=c(0.7, 0.8), legend.background = element_rect(fill="transparent"))

qplot(year, value * 100, data=subset(table.ts11.melted, variable %in% c("Simulated inheritance 1", "Simulated inheritance 2", "Economic flow")), geom=c("line", "point"), color=variable, xlab = "Year", ylab= "Annual value of bequest and  gift (% national income)
") + xlim(1820,2100) + theme(legend.position=c(0.6, 0.8), legend.background = element_rect(fill="transparent")) + ggtitle("Figure 11.6. Observed and simulated inheritance flow, France 1820-2100")
```

